### ISSUE TITLE
False move ids in state

### ISSUE THREAD

**Issue by MarcoMeter** [dvruette/pygba#1]
Hi @dvruette 

thanks for making this great repo available!

I'm examining the state dictionary from the get_game_state function.
The move ids are always 0 for the 3rd and 4th move of a pokemon.

`state["party"][0]["box"]["substructs"][1]` outputs `{'moves': [21, 200, 0, 0], 'pp': [20, 15, 35, 20]}`

I observed this for all pokemon inside the player's party.

**Comment by MarcoMeter** [comment]
This seems to fix the issue in emerald_utils.py:389

```python
    substruct1 = PokemonSubstruct1([
        (x1 >> 0)  & 0xFFFF, 
        (x1 >> 16) & 0xFFFF, 
        (x2 >> 0)  & 0xFFFF,
        (x2 >> 16) & 0xFFFF,
    ], [
        (x3 >> 0)  & 0xFF, 
        (x3 >> 8)  & 0xFF,
        (x3 >> 16) & 0xFF,
        (x3 >> 24) & 0xFF,
    ])
```

**Comment by dvruette** [comment]
Hi Marco, thanks for pointing this out! It indeed seems be a bug in the parsing code, I've pushed the fix you suggested. Until I push it to PyPi as well, please update the package directly from `main`.

Also, in case you haven't already, check out my other (improved) Emerald wrapper I used to train a PPO agent on: https://github.com/dvruette/pokemon-emerald-experiments/blob/master/baselines/emerald_wrapper.py
