### ISSUE TITLE
Box pokemon conflicting information

### ISSUE THREAD

**Issue by MarcoMeter** [dvruette/pygba#2]
Hi,

I came across another bug. The values of a pokemon inside a box seems broken.
Here is an example for a Poochyena:

```
{'personality': 2499805184, 'otId': 700220081, 'nickname': '/っモPOOCHYE', 'language': 200, 'flags': 187, 'otName': '', 'markings': 255, 'checksum': 65535, 'substructs': ({'species': 20666, 'heldItem': 115, 'experience': 7557306, 'ppBonuses': 186, 'friendship': 80}, {'moves': [33395, 7868, 20667, 16499], 'pp': [186, 80, 115, 0]}, {'hpEV': 252, 'attackEV': 80, 'defenseEV': 115, 'speedEV': 0, 'spAttackEV': 169, 'spDefenseEV': 212, 'cool': 82, 'beauty': 53, 'cute': 129, 'smart': 131, 'tough': 121, 'sheen': 0}, {'pokerus': 186, 'metLocation': 29520, 'metLevel': 115, 'metGame': 2, 'pokeball': 4, 'otGender': 0, 'hpIV': 26, 'attackIV': 5, 'defenseIV': 20, 'speedIV': 6, 'spAttackIV': 7, 'spDefenseIV': 0, 'isEgg': 0, 'abilityNum': 0, 'ribbons': 594759866})}
```

The key "maxHp" is missing and obviously the ids for species and moves is conflicting as well as the number of pps.
@dvruette , do you have any idea on how to approach this?

It would be also great to figure out the box position.

**Comment by MarcoMeter** [comment]
If helpful, I created a jupyter notebook to ease reproducing this issue:
[juypter notebook at colab](https://drive.google.com/file/d/1pNsv--kpir9sDJVjOxDNyaQLiBFz7pOP/view?usp=sharing)
[pokemon_storage_data.pkl](https://drive.google.com/file/d/1BeWenUqBQXs0XVtdLcBM5vn4ibDmPERH/view?usp=sharing)

**Comment by dvruette** [comment]
Hi Marco, thanks for the ping! Is it a bug that occurs for every box pokemon or only in some cases? Looking at the example above, it could be some misalignment in the way the bytes are being parsed.

Right now I don't have time to look into it (coming weeks are looking quite busy as well..), but the awesome pret project has a decompiled repository with the pokemon emerald source code: https://github.com/pret/pokeemerald

Here's also the layout of the BoxPokemon struct: https://github.com/pret/pokeemerald/blob/5dbd90b917c2474cd89b45b2c2e33e1544c43b0e/include/pokemon.h#L196

First thing I would check is to make sure that the parsing code uses the correct offsets and ranges.

**Comment by mrgriffin** [comment]
Hi, I'm a pret/pokeemerald user (/occasional contributor).

> The key "maxHp" is missing

fwiw, `maxHP` is only in `Pokemon`, not `BoxPokemon`. It gets computed when the Pokémon is withdrawn from the PC (ultimately by [`CalculateMonStats`](https://github.com/pret/pokeemerald/blob/master/src/pokemon.c#L2823) iirc).

**Comment by MarcoMeter** [comment]
Here is the fix for [line 524](https://github.com/dvruette/pygba/blob/main/src/pygba/game_wrappers/utils/emerald_utils.py#L524):

```
parse_box_pokemon(pokemon_storage.boxes[i + 3 : i + box_mon_size + 3])
```

Thanks  @mrgriffin @dvruette !

**Comment by mrgriffin** [comment]
I think there are three bytes of padding missing after `currentBox` (pret has the offsets for boxes listed incorrectly, the next member starts at byte 4).

**Comment by MarcoMeter** [comment]
As an alterenative fix:

```python
PokemonStorage_spec = (
    ("currentBox", "B"),
    ("Unknown", f"{3}s"),
    ("boxes", f"{struct.calcsize(BoxPokemon_format) * TOTAL_BOXES_COUNT * IN_BOX_COUNT}s"),
    ("boxNames", f"{TOTAL_BOXES_COUNT * (BOX_NAME_LENGTH + 1)}s"),
    ("boxWallpapers", f"{TOTAL_BOXES_COUNT}s"),
)
```

**Comment by dvruette** [comment]
Thanks everyone! @MarcoMeter I've just pushed your proposed fix to master.
